package com.strwatcher.noder.base

const val FloatNodeType = "Float"
const val IntNodeType = "Int"
const val StringNodeType = "String"
const val ImageNodeType = "Image"
const val StartNodeType = "Start"
const val EndNodeType = "End"
const val AddImageNodeType = "AddImage"
const val AddTextNodeType = "AddText"
const val BlurNodeType = "Blur"
const val  BrightnessNodeType = "Brightness"
const val GrayFilterNodeType = "Gray"
const val InvertNodeType = "Invert"
const val MoveNodeType = "Move"
const val RotationNodeType = "Rotation"
const val ScaleNodeType = "Scale"
const val SepiaNodeType = "Sepia"